version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /
      - /benchmark
      - /fuzz
      - /xtask
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /scripts/documentation-tools
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
