//! Medium filesystem differential evidence over an explicitly bounded payload space.

use std::error::Error;
use std::fs;

use keep::{AdmittedSegmentRecord, ObservedSegmentStage, SegmentRecordLimit, StagedSegment};

use super::{Observer, publisher, sandbox};

#[test]
fn observed_short_writes_match_plain_writes_across_generated_payload_lengths()
-> Result<(), Box<dyn Error>> {
    // Ascending exhaustive length exploration reports the smallest failing
    // member of this input family. Empty segments have an independent golden.
    for length in 1..=64 {
        let payload: Vec<_> = b"generated bytes"
            .iter()
            .copied()
            .cycle()
            .take(length)
            .collect();
        let plain_dir = sandbox::TestDirectory::create(&format!("plain-stage-{length}"))?;
        let observed_dir = sandbox::TestDirectory::create(&format!("observed-stage-{length}"))?;
        let plain = publisher(&plain_dir)?;
        let observed = publisher(&observed_dir)?;
        let plain_sealed =
            StagedSegment::begin(plain.create_segment_stage()?, SegmentRecordLimit::MAXIMUM)?
                .append(AdmittedSegmentRecord::for_chunk(&payload)?)?
                .seal()?;
        let decorated =
            ObservedSegmentStage::new(observed.create_segment_stage()?, Observer::Prefixes);
        let observed_sealed = StagedSegment::begin(decorated, SegmentRecordLimit::MAXIMUM)?
            .append(AdmittedSegmentRecord::for_chunk(&payload)?)?
            .seal()?
            .without_observer();
        assert_eq!(
            fs::read(observed_dir.path().join("staging/current.seg"))?,
            fs::read(plain_dir.path().join("staging/current.seg"))?,
            "observed/plain storage differs for generated payload length {length}"
        );
        drop(plain_sealed);
        drop(observed_sealed);
        drop(plain);
        drop(observed);
        plain_dir.remove()?;
        observed_dir.remove()?;
    }
    Ok(())
}
