// The one contiguous stable crash-boundary vocabulary, spliced into
// `expected()` by the contract file.
&[
    (
        DurabilityCrashPoint::CreateSegmentStage,
        "KEEP-CRASH-001",
        Segment,
    ),
    (
        DurabilityCrashPoint::WriteSegmentHeader,
        "KEEP-CRASH-002",
        Segment,
    ),
    (
        DurabilityCrashPoint::AppendSegmentRecord,
        "KEEP-CRASH-003",
        Segment,
    ),
    (
        DurabilityCrashPoint::FlushSegmentRecordPrefix,
        "KEEP-CRASH-004",
        Segment,
    ),
    (
        DurabilityCrashPoint::SynchronizeSegmentRecordPrefix,
        "KEEP-CRASH-005",
        Segment,
    ),
    (
        DurabilityCrashPoint::AppendSegmentSeal,
        "KEEP-CRASH-006",
        Segment,
    ),
    (
        DurabilityCrashPoint::FlushSealedSegment,
        "KEEP-CRASH-007",
        Segment,
    ),
    (
        DurabilityCrashPoint::SynchronizeSealedSegment,
        "KEEP-CRASH-008",
        Segment,
    ),
    (DurabilityCrashPoint::LinkSegment, "KEEP-CRASH-009", Segment),
    (
        DurabilityCrashPoint::SynchronizeSegmentPool,
        "KEEP-CRASH-010",
        Segment,
    ),
    (
        DurabilityCrashPoint::RemoveSegmentStage,
        "KEEP-CRASH-011",
        Segment,
    ),
    (
        DurabilityCrashPoint::SynchronizeStagingAfterSegment,
        "KEEP-CRASH-012",
        Segment,
    ),
    (
        DurabilityCrashPoint::CreateCatalogStage,
        "KEEP-CRASH-013",
        Catalog,
    ),
    (
        DurabilityCrashPoint::WriteCatalog,
        "KEEP-CRASH-014",
        Catalog,
    ),
    (
        DurabilityCrashPoint::FlushCatalog,
        "KEEP-CRASH-015",
        Catalog,
    ),
    (
        DurabilityCrashPoint::SynchronizeCatalog,
        "KEEP-CRASH-016",
        Catalog,
    ),
    (DurabilityCrashPoint::LinkCatalog, "KEEP-CRASH-017", Catalog),
    (
        DurabilityCrashPoint::SynchronizeCatalogPool,
        "KEEP-CRASH-018",
        Catalog,
    ),
    (
        DurabilityCrashPoint::RemoveCatalogStage,
        "KEEP-CRASH-019",
        Catalog,
    ),
    (
        DurabilityCrashPoint::SynchronizeStagingAfterCatalog,
        "KEEP-CRASH-020",
        Catalog,
    ),
    (
        DurabilityCrashPoint::CreateHeadStage,
        "KEEP-CRASH-021",
        Head,
    ),
    (DurabilityCrashPoint::WriteHead, "KEEP-CRASH-022", Head),
    (DurabilityCrashPoint::FlushHead, "KEEP-CRASH-023", Head),
    (
        DurabilityCrashPoint::SynchronizeHead,
        "KEEP-CRASH-024",
        Head,
    ),
    (DurabilityCrashPoint::ReplaceHead, "KEEP-CRASH-025", Head),
    (
        DurabilityCrashPoint::SynchronizeRootAfterHead,
        "KEEP-CRASH-026",
        Head,
    ),
    (
        DurabilityCrashPoint::RemoveRecoveryStage,
        "KEEP-CRASH-027",
        RecoveryDiscard,
    ),
    (
        DurabilityCrashPoint::SynchronizeStagingAfterRecovery,
        "KEEP-CRASH-028",
        RecoveryDiscard,
    ),
    (
        DurabilityCrashPoint::RemoveRecoveryHead,
        "KEEP-CRASH-029",
        RecoveryDiscard,
    ),
    (
        DurabilityCrashPoint::SynchronizeRootAfterRecovery,
        "KEEP-CRASH-030",
        RecoveryDiscard,
    ),
    (
        DurabilityCrashPoint::OpenAndLockWriterFile,
        "KEEP-CRASH-031",
        Initialization,
    ),
    (
        DurabilityCrashPoint::CreateStagingDirectory,
        "KEEP-CRASH-032",
        Initialization,
    ),
    (
        DurabilityCrashPoint::CreateSegmentPoolDirectory,
        "KEEP-CRASH-033",
        Initialization,
    ),
    (
        DurabilityCrashPoint::CreateCatalogPoolDirectory,
        "KEEP-CRASH-034",
        Initialization,
    ),
    (
        DurabilityCrashPoint::SynchronizeRootAfterInitialization,
        "KEEP-CRASH-035",
        Initialization,
    ),
    (
        DurabilityCrashPoint::WriteRootStage,
        "KEEP-CRASH-036",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeRootStage,
        "KEEP-CRASH-037",
        Retention,
    ),
    (
        DurabilityCrashPoint::AdmitRootNamespace,
        "KEEP-CRASH-038",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeRootsAfterNamespace,
        "KEEP-CRASH-039",
        Retention,
    ),
    (DurabilityCrashPoint::LinkRoot, "KEEP-CRASH-040", Retention),
    (
        DurabilityCrashPoint::SynchronizeRootNamespace,
        "KEEP-CRASH-041",
        Retention,
    ),
    (
        DurabilityCrashPoint::WriteManifestStage,
        "KEEP-CRASH-042",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeManifestStage,
        "KEEP-CRASH-043",
        Retention,
    ),
    (
        DurabilityCrashPoint::LinkManifest,
        "KEEP-CRASH-044",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeManifestPool,
        "KEEP-CRASH-045",
        Retention,
    ),
    (
        DurabilityCrashPoint::WriteHeadStage,
        "KEEP-CRASH-046",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeHeadStage,
        "KEEP-CRASH-047",
        Retention,
    ),
    (
        DurabilityCrashPoint::ReplaceRetentionHead,
        "KEEP-CRASH-048",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeRetentionNamespace,
        "KEEP-CRASH-049",
        Retention,
    ),
    (
        DurabilityCrashPoint::RemoveRootStage,
        "KEEP-CRASH-050",
        Retention,
    ),
    (
        DurabilityCrashPoint::RemoveManifestStage,
        "KEEP-CRASH-051",
        Retention,
    ),
    (
        DurabilityCrashPoint::SynchronizeRetentionCleanup,
        "KEEP-CRASH-052",
        Retention,
    ),
    (
        DurabilityCrashPoint::MigrationWriteIntentStage,
        "KEEP-CRASH-053",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeIntentStage,
        "KEEP-CRASH-054",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationLinkIntent,
        "KEEP-CRASH-055",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterIntent,
        "KEEP-CRASH-056",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationRemoveIntentStage,
        "KEEP-CRASH-057",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterIntentCleanup,
        "KEEP-CRASH-058",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationAdmitReaderFence,
        "KEEP-CRASH-059",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationAdmitNamespacePrefix,
        "KEEP-CRASH-060",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterNamespace,
        "KEEP-CRASH-061",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationWriteMarkerStage,
        "KEEP-CRASH-062",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeMarkerStage,
        "KEEP-CRASH-063",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationLinkMarker,
        "KEEP-CRASH-064",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterMarker,
        "KEEP-CRASH-065",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationRemoveMarkerStage,
        "KEEP-CRASH-066",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterMarkerCleanup,
        "KEEP-CRASH-067",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationWriteReceiptStage,
        "KEEP-CRASH-068",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeReceiptStage,
        "KEEP-CRASH-069",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationLinkReceipt,
        "KEEP-CRASH-070",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterReceipt,
        "KEEP-CRASH-071",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationRemoveReceiptStage,
        "KEEP-CRASH-072",
        Migration,
    ),
    (
        DurabilityCrashPoint::MigrationSynchronizeRootAfterReceiptCleanup,
        "KEEP-CRASH-073",
        Migration,
    ),
    (
        DurabilityCrashPoint::GcWriteIntentStage,
        "KEEP-CRASH-074",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcSynchronizeIntentStage,
        "KEEP-CRASH-075",
        Gc,
    ),
    (DurabilityCrashPoint::GcLinkIntent, "KEEP-CRASH-076", Gc),
    (
        DurabilityCrashPoint::GcSynchronizeGcAfterIntent,
        "KEEP-CRASH-077",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcRemoveIntentStage,
        "KEEP-CRASH-078",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcSynchronizeGcAfterIntentCleanup,
        "KEEP-CRASH-079",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcUnlinkCandidate,
        "KEEP-CRASH-080",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcSynchronizeSegmentPool,
        "KEEP-CRASH-081",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcWriteReceiptStage,
        "KEEP-CRASH-082",
        Gc,
    ),
    (
        DurabilityCrashPoint::GcSynchronizeReceiptStage,
        "KEEP-CRASH-083",
        Gc,
    ),
    (DurabilityCrashPoint::GcReplaceReceipt, "KEEP-CRASH-084", Gc),
    (
        DurabilityCrashPoint::GcSynchronizeGcAfterReceipt,
        "KEEP-CRASH-085",
        Gc,
    ),
    (DurabilityCrashPoint::GcRemoveIntent, "KEEP-CRASH-086", Gc),
    (
        DurabilityCrashPoint::GcSynchronizeGcAfterIntentRemoval,
        "KEEP-CRASH-087",
        Gc,
    ),
]
