//! Canonical catalog emission failures.

use std::collections::TryReserveError;
use std::error::Error;
use std::fmt;

use super::{CatalogDecodeError, SegmentDigest, SegmentReadError, SegmentRecordIdentity};
use crate::{CatalogDigest, CatalogGeneration, CatalogLengthError};

/// Failure to derive one canonical catalog from admitted segments.
#[derive(Debug)]
pub enum CatalogEncodeError {
    /// Generation 1 was given a predecessor digest.
    UnexpectedPredecessor {
        /// Supplied predecessor that generation 1 forbids.
        observed: CatalogDigest,
    },
    /// A later generation omitted its required predecessor digest.
    MissingPredecessor {
        /// Later generation being encoded.
        generation: CatalogGeneration,
    },
    /// A supplied segment has no record that the catalog can reference.
    UnreferencedSegment {
        /// Exact unreferenced physical segment.
        segment_digest: SegmentDigest,
    },
    /// Summing admitted segment record counts overflowed.
    EntryCountArithmetic,
    /// The aggregate record count exceeded the format bound.
    EntryCountOutOfBounds {
        /// Largest version-1 entry count.
        maximum: u64,
        /// Exact observed aggregate.
        observed: u64,
    },
    /// The canonical catalog length was not representable.
    CatalogLength {
        /// Checked length refusal.
        source: CatalogLengthError,
    },
    /// The canonical catalog length exceeded the host address space.
    HostLength {
        /// Protocol length that the host could not represent.
        observed: u64,
    },
    /// Memory reservation for the exact bounded entry set failed.
    Allocation {
        /// Exact number of entries being retained.
        entry_count: u64,
        /// Preserved allocation source.
        source: TryReserveError,
    },
    /// Generated bytes failed independent canonical decoder verification.
    Verification {
        /// Preserved decoder refusal.
        source: CatalogDecodeError,
    },
    /// Immutable segment revalidation failed while deriving coordinates.
    Segment {
        /// Exact segment being traversed.
        segment_digest: SegmentDigest,
        /// Preserved segment refusal.
        source: Box<SegmentReadError>,
    },
    /// Two admitted segments supplied the same logical identity.
    DuplicateIdentity {
        /// Exact duplicated logical identity.
        identity: SegmentRecordIdentity,
    },
}

impl fmt::Display for CatalogEncodeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnexpectedPredecessor { .. } => {
                formatter.write_str("catalog generation 1 cannot name a predecessor")
            }
            Self::MissingPredecessor { generation } => write!(
                formatter,
                "catalog generation {} requires a predecessor",
                generation.get()
            ),
            Self::UnreferencedSegment { .. } => {
                formatter.write_str("catalog input contains an unreferenced segment")
            }
            Self::EntryCountArithmetic => formatter.write_str("catalog entry count overflowed"),
            Self::EntryCountOutOfBounds { maximum, observed } => write!(
                formatter,
                "catalog entry count {observed} exceeds maximum {maximum}"
            ),
            Self::CatalogLength { .. } => {
                formatter.write_str("canonical catalog length is invalid")
            }
            Self::HostLength { observed } => write!(
                formatter,
                "catalog length {observed} exceeds the host address space"
            ),
            Self::Allocation { entry_count, .. } => {
                write!(
                    formatter,
                    "catalog allocation for {entry_count} entries failed"
                )
            }
            Self::Verification { .. } => {
                formatter.write_str("generated catalog verification failed")
            }
            Self::Segment { .. } => formatter.write_str("catalog segment revalidation failed"),
            Self::DuplicateIdentity { .. } => {
                formatter.write_str("catalog input contains a duplicate logical identity")
            }
        }
    }
}

impl Error for CatalogEncodeError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::CatalogLength { source } => Some(source),
            Self::Allocation { source, .. } => Some(source),
            Self::Verification { source } => Some(source),
            Self::Segment { source, .. } => Some(source),
            Self::UnexpectedPredecessor { .. }
            | Self::MissingPredecessor { .. }
            | Self::UnreferencedSegment { .. }
            | Self::EntryCountArithmetic
            | Self::EntryCountOutOfBounds { .. }
            | Self::HostLength { .. }
            | Self::DuplicateIdentity { .. } => None,
        }
    }
}
