//! Canonical format-boundary adapters.
//!
//! This module owns decoding raw input into validated domain types, encoding
//! validated domain types into canonical bytes, and exact immutable-segment
//! ingress and egress. It does not own identity calculation, logical layout
//! policy, physical location, namespace publication, recovery, or retention
//! policy.

mod admitted_catalog;
mod admitted_recovery_stage_bytes;
mod admitted_segment;
mod admitted_segment_record;
mod blob_id_binary;
mod blob_id_binary_error;
mod blob_id_text;
mod blob_id_text_error;
mod canonical_catalog;
mod canonical_publication_head;
mod catalog_admission;
mod catalog_admission_error;
mod catalog_admission_error_display;
mod catalog_allocation_phase;
mod catalog_decode_error;
mod catalog_decode_error_display;
mod catalog_decoder;
mod catalog_encode_error;
mod catalog_encoder;
mod catalog_encoding_entry;
mod catalog_entries;
mod catalog_entry_decode_error;
mod catalog_entry_decode_error_display;
mod catalog_entry_decoder;
mod catalog_entry_fields;
mod catalog_entry_plan;
mod catalog_entry_sequence;
mod catalog_header_decoder;
mod catalog_header_encoding;
mod catalog_integrity;
mod catalog_publication;
mod catalog_publication_error;
mod catalog_publication_execution;
mod catalog_publication_expectation;
mod catalog_publication_outcome;
mod catalog_publication_phase;
mod catalog_publication_readiness;
mod catalog_publication_receipt;
mod catalog_publication_storage;
mod catalog_record_binding;
mod catalog_restart_artifact;
mod catalog_restart_byte_limit;
mod catalog_restart_error;
mod catalog_restart_io;
mod catalog_restart_loader;
mod catalog_restart_phase;
mod catalog_restart_policy;
mod catalog_restart_segments;
mod catalog_snapshot;
mod catalog_snapshot_admission;
mod catalog_snapshot_error;
mod catalog_successor;
mod catalog_transition;
mod catalog_transition_error;
mod checksummed_catalog;
mod checksummed_publication_head;
mod checksummed_segment_record;
mod closed_segment;
mod decoded_catalog_entry;
mod filesystem_catalog_artifact;
mod filesystem_catalog_catalog;
mod filesystem_catalog_current;
mod filesystem_catalog_head;
mod filesystem_catalog_publication_error;
mod filesystem_catalog_publisher;
#[cfg(test)]
mod filesystem_catalog_publisher_tests;
mod filesystem_catalog_segment;
mod filesystem_catalog_snapshot;
mod filesystem_catalog_storage;
mod filesystem_initialization_namespace;
mod filesystem_initialization_storage;
mod filesystem_platform_admission;
mod filesystem_platform_admission_error;
mod filesystem_platform_profile;
mod filesystem_publisher_authority;
mod filesystem_recovery_inventory_reader;
mod filesystem_recovery_inventory_scan;
#[cfg(all(test, unix))]
mod filesystem_recovery_inventory_tests;
mod filesystem_recovery_namespace;
mod filesystem_recovery_next_head_candidate;
mod filesystem_recovery_next_head_finalization_open_error;
mod filesystem_recovery_next_head_finalization_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_next_head_finalization_tests;
mod filesystem_recovery_next_head_finalizer;
mod filesystem_recovery_segment_resume_open_error;
mod filesystem_recovery_segment_resume_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_segment_resume_tests;
mod filesystem_recovery_segment_resumer;
mod filesystem_recovery_segment_stage;
mod filesystem_recovery_stage;
mod filesystem_recovery_stage_completer;
mod filesystem_recovery_stage_completion_open_error;
mod filesystem_recovery_stage_completion_pool;
mod filesystem_recovery_stage_completion_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_completion_tests;
mod filesystem_recovery_stage_discard_open_error;
mod filesystem_recovery_stage_discard_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_discard_tests;
mod filesystem_recovery_stage_discarder;
mod filesystem_recovery_stage_error;
mod filesystem_recovery_stage_error_display;
mod filesystem_recovery_stage_materialization;
mod filesystem_recovery_stage_sync;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_tests;
mod filesystem_segment_stage;
#[cfg(test)]
mod filesystem_segment_stage_tests;
mod filesystem_store_initializer;
#[cfg(test)]
mod filesystem_store_initializer_tests;
#[cfg(test)]
#[path = "../../tests/segment_filesystem_stage/sandbox.rs"]
mod filesystem_test_sandbox;
mod filesystem_writer_lock;
mod framed_blake3;
mod layout_decode_error;
mod layout_decode_error_display;
mod layout_decode_policy;
mod layout_encode_error;
mod layout_header_decoder;
mod layout_id_binary;
mod layout_id_binary_error;
mod layout_id_text;
mod layout_id_text_error;
mod layout_record;
mod layout_record_decoder;
mod layout_record_encoder;
mod layout_record_format;
mod layout_record_framing;
mod loaded_segment;
mod lower_hex;
mod opened_reusable_segment;
mod physical_pool_name;
mod publication_head_decode_error;
mod publication_head_decode_error_display;
mod publication_head_decoder;
mod publication_head_encoder;
mod recovery_catalog_stage;
mod recovery_catalog_stage_error;
mod recovery_entry_name;
mod recovery_entry_role;
mod recovery_fixed_field_prefix;
mod recovery_inventory;
mod recovery_inventory_error;
mod recovery_inventory_limit;
mod recovery_inventory_operation;
mod recovery_inventory_storage;
mod recovery_name_classification;
mod recovery_name_classification_error;
mod recovery_name_manifest;
mod recovery_namespace;
mod recovery_next_head_finalization_error;
mod recovery_next_head_finalization_executor;
mod recovery_next_head_finalization_outcome;
mod recovery_next_head_finalization_plan_error;
mod recovery_next_head_finalization_planner;
mod recovery_next_head_finalization_readiness;
mod recovery_next_head_finalization_receipt;
mod recovery_next_head_finalization_request;
mod recovery_next_head_finalization_storage;
mod recovery_next_head_finalization_storage_error;
mod recovery_next_head_finalization_target;
mod recovery_next_head_stage;
mod recovery_next_head_stage_error;
mod recovery_pool_name;
mod recovery_pool_name_error;
mod recovery_publication_fixed_framing;
mod recovery_publication_stage_classifier;
mod recovery_required_entry;
mod recovery_segment_classifier;
mod recovery_segment_fixed_framing;
mod recovery_segment_resume_error;
mod recovery_segment_resume_executor;
mod recovery_segment_resume_plan_error;
mod recovery_segment_resume_planner;
mod recovery_segment_resume_request;
mod recovery_segment_resume_state;
mod recovery_segment_resume_storage;
mod recovery_segment_resume_storage_error;
mod recovery_segment_stage;
mod recovery_segment_stage_error;
mod recovery_segment_truncation;
mod recovery_stage;
mod recovery_stage_assessment;
mod recovery_stage_assessment_error;
mod recovery_stage_assessor;
mod recovery_stage_byte_admission;
mod recovery_stage_byte_admission_error;
mod recovery_stage_completion_error;
mod recovery_stage_completion_executor;
mod recovery_stage_completion_plan_error;
mod recovery_stage_completion_planner;
mod recovery_stage_completion_pool;
mod recovery_stage_completion_receipt;
mod recovery_stage_completion_request;
mod recovery_stage_completion_storage;
mod recovery_stage_completion_storage_error;
mod recovery_stage_completion_target;
mod recovery_stage_discard_error;
mod recovery_stage_discard_executor;
mod recovery_stage_discard_outcome;
mod recovery_stage_discard_plan_error;
mod recovery_stage_discard_planner;
mod recovery_stage_discard_reason;
mod recovery_stage_discard_receipt;
mod recovery_stage_discard_request;
mod recovery_stage_discard_storage;
mod recovery_stage_discard_storage_error;
mod recovery_stage_evidence;
mod recovery_stage_fingerprint;
mod recovery_stage_fingerprint_algorithm;
mod recovery_stage_fingerprint_error;
mod recovery_stage_fingerprinter;
mod recovery_stage_length;
mod recovery_stage_metadata;
mod recovery_stage_metadata_error;
mod recovery_stage_parent;
mod recovery_stage_pool_outcome;
mod recovery_stage_synchronization_outcome;
#[cfg(feature = "repository-tasks")]
mod repository_initialization_storage;
pub(crate) mod retention;
mod sealed_segment;
mod segment_digest;
mod segment_digest_builder;
mod segment_header;
mod segment_header_admission;
mod segment_header_decoder;
mod segment_header_encoding;
mod segment_header_error;
mod segment_header_error_display;
mod segment_identity_index;
mod segment_publication;
mod segment_publication_error;
mod segment_read_error;
mod segment_read_error_display;
mod segment_read_policy;
mod segment_reader;
mod segment_record_admission;
mod segment_record_admission_error;
mod segment_record_admission_error_display;
mod segment_record_checksum;
mod segment_record_cursor;
mod segment_record_cursor_decode;
mod segment_record_decode_error;
mod segment_record_decode_error_display;
mod segment_record_decoder;
mod segment_record_header;
mod segment_record_header_admission;
mod segment_record_header_decoder;
mod segment_record_header_encoding;
mod segment_record_header_error;
mod segment_record_header_error_display;
mod segment_record_identity;
mod segment_record_identity_admission;
mod segment_record_identity_encoding;
mod segment_record_kind;
mod segment_record_length;
mod segment_record_limit;
mod segment_record_payload_length;
mod segment_records;
mod segment_seal;
mod segment_seal_admission;
mod segment_seal_builder;
mod segment_seal_decoder;
mod segment_seal_encoding;
mod segment_seal_envelope;
mod segment_seal_envelope_admission;
mod segment_seal_error;
mod segment_seal_error_display;
mod segment_seal_hash;
mod segment_stage;
mod segment_stage_create_error;
mod segment_stage_create_error_display;
mod segment_stage_write;
mod segment_write_error;
mod segment_write_error_display;
mod segment_write_phase;
mod staged_segment;
mod storage_profile_id_text;
mod storage_profile_id_text_error;
mod store_initialization;
mod store_initialization_error;
mod store_initialization_phase;
mod store_initialization_receipt;
mod store_initialization_storage;
mod sync_capable_directory;
#[cfg(test)]
#[path = "../../tests/support/mod.rs"]
mod test_support;
mod writer_lock_acquire_error;
mod writer_lock_acquire_phase;

pub use admitted_catalog::AdmittedCatalog;
pub use admitted_recovery_stage_bytes::AdmittedRecoveryStageBytes;
pub use admitted_segment::AdmittedSegment;
pub use admitted_segment_record::AdmittedSegmentRecord;
pub use blob_id_binary_error::BlobIdBinaryParseError;
pub use blob_id_text_error::BlobIdTextParseError;
pub use canonical_catalog::CanonicalCatalog;
pub use canonical_publication_head::CanonicalPublicationHead;
pub use catalog_admission_error::CatalogAdmissionError;
pub use catalog_allocation_phase::CatalogAllocationPhase;
pub use catalog_decode_error::CatalogDecodeError;
pub use catalog_encode_error::CatalogEncodeError;
pub use catalog_entry_decode_error::CatalogEntryDecodeError;
pub use catalog_publication::publish_catalog_generation;
pub use catalog_publication_error::CatalogPublicationError;
pub use catalog_publication_expectation::CatalogPublicationExpectation;
pub use catalog_publication_outcome::CatalogPublicationOutcome;
pub use catalog_publication_phase::CatalogPublicationPhase;
pub use catalog_publication_readiness::CatalogPublicationReadiness;
pub use catalog_publication_receipt::CatalogPublicationReceipt;
pub use catalog_publication_storage::CatalogPublicationStorage;
pub use catalog_restart_artifact::CatalogRestartArtifact;
pub use catalog_restart_byte_limit::{CatalogRestartByteLimit, CatalogRestartByteLimitError};
pub use catalog_restart_error::CatalogRestartError;
pub use catalog_restart_phase::CatalogRestartPhase;
pub use catalog_restart_policy::CatalogRestartPolicy;
pub use catalog_snapshot::CatalogSnapshot;
pub use catalog_snapshot_error::CatalogSnapshotError;
pub use catalog_successor::CatalogSuccessor;
pub use catalog_transition_error::CatalogTransitionError;
pub use checksummed_catalog::ChecksummedCatalog;
pub use checksummed_publication_head::ChecksummedPublicationHead;
pub use checksummed_segment_record::ChecksummedSegmentRecord;
pub use closed_segment::ClosedSegment;
pub use filesystem_catalog_publication_error::FilesystemCatalogPublicationError;
pub use filesystem_catalog_publisher::FilesystemCatalogPublisher;
pub use filesystem_catalog_snapshot::FilesystemCatalogSnapshot;
pub use filesystem_platform_admission::FilesystemPlatformAdmission;
pub use filesystem_platform_admission_error::FilesystemPlatformAdmissionError;
pub use filesystem_recovery_inventory_reader::FilesystemRecoveryInventoryReader;
pub use filesystem_recovery_next_head_finalization_open_error::FilesystemRecoveryNextHeadFinalizationOpenError;
pub use filesystem_recovery_next_head_finalizer::FilesystemRecoveryNextHeadFinalizer;
pub use filesystem_recovery_segment_resume_open_error::FilesystemRecoverySegmentResumeOpenError;
pub use filesystem_recovery_segment_resumer::FilesystemRecoverySegmentResumer;
pub use filesystem_recovery_segment_stage::FilesystemRecoverySegmentStage;
pub use filesystem_recovery_stage_completer::FilesystemRecoveryStageCompleter;
pub use filesystem_recovery_stage_completion_open_error::FilesystemRecoveryStageCompletionOpenError;
pub use filesystem_recovery_stage_discard_open_error::FilesystemRecoveryStageDiscardOpenError;
pub use filesystem_recovery_stage_discarder::FilesystemRecoveryStageDiscarder;
pub use filesystem_recovery_stage_error::{
    FilesystemRecoveryStageError, RecoveryStageNamespacePhase,
};
pub use filesystem_segment_stage::FilesystemSegmentStage;
pub use filesystem_writer_lock::FilesystemWriterLock;
pub use layout_decode_error::LayoutDecodeError;
pub use layout_decode_policy::LayoutDecodePolicy;
pub use layout_encode_error::LayoutEncodeError;
pub use layout_id_binary_error::LayoutIdBinaryParseError;
pub use layout_id_text_error::LayoutIdTextParseError;
pub use layout_record::CanonicalLayoutRecord;
pub use opened_reusable_segment::OpenedReusableSegment;
pub use publication_head_decode_error::PublicationHeadDecodeError;
pub use recovery_catalog_stage::RecoveryCatalogStage;
pub use recovery_catalog_stage_error::RecoveryCatalogStageError;
pub use recovery_entry_name::{RecoveryEntryName, RecoveryEntryNameError};
pub use recovery_entry_role::RecoveryEntryRole;
pub use recovery_inventory::{RecoveryInventory, RecoveryInventoryEntry, read_recovery_inventory};
pub use recovery_inventory_error::RecoveryInventoryError;
pub use recovery_inventory_limit::{RecoveryInventoryLimit, RecoveryInventoryLimitError};
pub use recovery_inventory_operation::RecoveryInventoryOperation;
pub use recovery_inventory_storage::RecoveryInventoryStorage;
pub use recovery_name_classification::classify_recovery_names;
pub use recovery_name_classification_error::RecoveryNameClassificationError;
pub use recovery_name_manifest::{RecoveryNameManifest, RecoveryNamedEntry};
pub use recovery_namespace::RecoveryNamespace;
pub use recovery_next_head_finalization_error::RecoveryNextHeadFinalizationError;
pub use recovery_next_head_finalization_executor::execute_recovery_next_head_finalization;
pub use recovery_next_head_finalization_outcome::RecoveryNextHeadFinalizationOutcome;
pub use recovery_next_head_finalization_plan_error::RecoveryNextHeadFinalizationPlanError;
pub use recovery_next_head_finalization_planner::plan_recovery_next_head_finalization;
pub use recovery_next_head_finalization_readiness::RecoveryNextHeadFinalizationReadiness;
pub use recovery_next_head_finalization_receipt::RecoveryNextHeadFinalizationReceipt;
pub use recovery_next_head_finalization_request::RecoveryNextHeadFinalizationRequest;
pub use recovery_next_head_finalization_storage::RecoveryNextHeadFinalizationStorage;
pub use recovery_next_head_finalization_storage_error::RecoveryNextHeadFinalizationStorageError;
pub use recovery_next_head_finalization_target::RecoveryNextHeadFinalizationTarget;
pub use recovery_next_head_stage::RecoveryNextHeadStage;
pub use recovery_next_head_stage_error::RecoveryNextHeadStageError;
pub use recovery_pool_name_error::RecoveryPoolNameError;
pub use recovery_publication_stage_classifier::{
    classify_recovery_catalog_stage, classify_recovery_next_head_stage,
};
pub use recovery_required_entry::RecoveryRequiredEntry;
pub use recovery_segment_classifier::classify_recovery_segment_stage;
pub use recovery_segment_resume_error::RecoverySegmentResumeError;
pub use recovery_segment_resume_executor::execute_recovery_segment_resume;
pub use recovery_segment_resume_plan_error::RecoverySegmentResumePlanError;
pub use recovery_segment_resume_planner::plan_recovery_segment_resume;
pub use recovery_segment_resume_request::RecoverySegmentResumeRequest;
pub use recovery_segment_resume_storage::RecoverySegmentResumeStorage;
pub use recovery_segment_resume_storage_error::RecoverySegmentResumeStorageError;
pub use recovery_segment_stage::{RecoverySegmentStage, ReusableRecoverySegment};
pub use recovery_segment_stage_error::RecoverySegmentStageError;
pub use recovery_segment_truncation::RecoverySegmentTruncation;
pub use recovery_stage::RecoveryStage;
pub use recovery_stage_assessment::RecoveryStageAssessment;
pub use recovery_stage_assessment_error::RecoveryStageAssessmentError;
pub use recovery_stage_assessor::assess_recovery_stage;
pub use recovery_stage_byte_admission::admit_recovery_stage_bytes;
pub use recovery_stage_byte_admission_error::RecoveryStageByteAdmissionError;
pub use recovery_stage_completion_error::RecoveryStageCompletionError;
pub use recovery_stage_completion_executor::execute_recovery_stage_completion;
pub use recovery_stage_completion_plan_error::RecoveryStageCompletionPlanError;
pub use recovery_stage_completion_planner::plan_recovery_stage_completion;
pub use recovery_stage_completion_pool::RecoveryStageCompletionPool;
pub use recovery_stage_completion_receipt::RecoveryStageCompletionReceipt;
pub use recovery_stage_completion_request::RecoveryStageCompletionRequest;
pub use recovery_stage_completion_storage::RecoveryStageCompletionStorage;
pub use recovery_stage_completion_storage_error::RecoveryStageCompletionStorageError;
pub use recovery_stage_completion_target::RecoveryStageCompletionTarget;
pub use recovery_stage_discard_error::RecoveryStageDiscardError;
pub use recovery_stage_discard_executor::execute_recovery_stage_discard;
pub use recovery_stage_discard_outcome::RecoveryStageDiscardOutcome;
pub use recovery_stage_discard_plan_error::RecoveryStageDiscardPlanError;
pub use recovery_stage_discard_planner::plan_recovery_stage_discard;
pub use recovery_stage_discard_reason::RecoveryStageDiscardReason;
pub use recovery_stage_discard_receipt::RecoveryStageDiscardReceipt;
pub use recovery_stage_discard_request::RecoveryStageDiscardRequest;
pub use recovery_stage_discard_storage::RecoveryStageDiscardStorage;
pub use recovery_stage_discard_storage_error::RecoveryStageDiscardStorageError;
pub use recovery_stage_evidence::RecoveryStageEvidence;
pub use recovery_stage_fingerprint::RecoveryStageFingerprint;
pub use recovery_stage_fingerprint_algorithm::RecoveryStageFingerprintAlgorithm;
pub use recovery_stage_fingerprint_error::RecoveryStageFingerprintError;
pub use recovery_stage_fingerprinter::fingerprint_recovery_stage;
pub use recovery_stage_length::RecoveryStageLength;
pub use recovery_stage_metadata::RecoveryStageMetadata;
pub use recovery_stage_metadata_error::RecoveryStageMetadataError;
pub use recovery_stage_parent::RecoveryStageParent;
pub use recovery_stage_pool_outcome::RecoveryStagePoolOutcome;
pub use recovery_stage_synchronization_outcome::RecoveryStageSynchronizationOutcome;
#[cfg(feature = "repository-tasks")]
pub use repository_initialization_storage::RepositoryInitializationStorage;
pub use sealed_segment::SealedSegment;
pub use segment_digest::SegmentDigest;
pub use segment_header::SegmentHeader;
pub use segment_header_error::SegmentHeaderError;
pub use segment_publication::SegmentPublication;
pub use segment_publication_error::SegmentPublicationError;
pub use segment_read_error::SegmentReadError;
pub use segment_read_policy::SegmentReadPolicy;
pub use segment_record_admission_error::SegmentRecordAdmissionError;
pub use segment_record_checksum::SegmentRecordChecksum;
pub use segment_record_decode_error::SegmentRecordDecodeError;
pub use segment_record_header::SegmentRecordHeader;
pub use segment_record_header_error::SegmentRecordHeaderError;
pub use segment_record_identity::SegmentRecordIdentity;
pub use segment_record_length::SegmentRecordLength;
pub use segment_record_limit::{SegmentRecordLimit, SegmentRecordLimitError};
pub use segment_record_payload_length::SegmentRecordPayloadLength;
pub use segment_records::SegmentRecords;
pub use segment_seal::SegmentSeal;
pub use segment_seal_error::SegmentSealError;
pub use segment_stage::SegmentStage;
pub use segment_stage_create_error::SegmentStageCreateError;
pub use segment_write_error::SegmentWriteError;
pub use segment_write_phase::{SegmentDurabilityPhase, SegmentWritePhase};
pub use staged_segment::StagedSegment;
pub use storage_profile_id_text_error::StorageProfileIdParseError;
pub use store_initialization::initialize_store;
pub use store_initialization_error::StoreInitializationError;
pub use store_initialization_phase::StoreInitializationPhase;
pub use store_initialization_receipt::StoreInitializationReceipt;
pub use store_initialization_storage::StoreInitializationStorage;
pub use writer_lock_acquire_error::WriterLockAcquireError;
pub use writer_lock_acquire_phase::WriterLockAcquirePhase;

use catalog_encoding_entry::CatalogEncodingEntry;
use catalog_entries::CatalogEntries;
use catalog_record_binding::CatalogRecordBinding;
use decoded_catalog_entry::DecodedCatalogEntry;
