//! Canonical format-boundary adapters.
//!
//! This module owns decoding raw input into validated domain types, encoding
//! validated domain types into canonical bytes, and exact immutable-segment
//! ingress and egress. It does not own identity calculation, logical layout
//! policy, physical location, namespace publication, recovery, or retention
//! policy.

mod admitted_catalog;
mod admitted_recovery_stage_bytes;
mod admitted_segment;
mod admitted_segment_record;
mod blob_id_binary;
mod blob_id_binary_error;
mod blob_id_text;
mod blob_id_text_error;
mod canonical_catalog;
mod canonical_publication_head;
mod catalog_admission;
mod catalog_admission_error;
mod catalog_admission_error_display;
mod catalog_allocation_phase;
mod catalog_decode_error;
mod catalog_decode_error_display;
mod catalog_decoder;
mod catalog_encode_error;
mod catalog_encoder;
mod catalog_encoding_entry;
mod catalog_entries;
mod catalog_entry_decode_error;
mod catalog_entry_decode_error_display;
mod catalog_entry_decoder;
mod catalog_entry_fields;
mod catalog_entry_plan;
mod catalog_entry_sequence;
mod catalog_header_decoder;
mod catalog_header_encoding;
mod catalog_integrity;
mod catalog_publication;
mod catalog_publication_error;
mod catalog_publication_execution;
mod catalog_publication_expectation;
mod catalog_publication_outcome;
mod catalog_publication_phase;
mod catalog_publication_readiness;
mod catalog_publication_receipt;
mod catalog_publication_storage;
mod catalog_record_binding;
mod catalog_restart_artifact;
mod catalog_restart_byte_limit;
mod catalog_restart_error;
mod catalog_restart_io;
mod catalog_restart_loader;
mod catalog_restart_phase;
mod catalog_restart_policy;
mod catalog_restart_segments;
mod catalog_snapshot;
mod catalog_snapshot_admission;
mod catalog_snapshot_error;
mod catalog_successor;
mod catalog_transition;
mod catalog_transition_error;
mod checksummed_catalog;
mod checksummed_publication_head;
mod checksummed_segment_record;
mod closed_segment;
mod decoded_catalog_entry;
mod exports;
mod filesystem_catalog_artifact;
mod filesystem_catalog_catalog;
mod filesystem_catalog_current;
mod filesystem_catalog_head;
mod filesystem_catalog_publication_error;
mod filesystem_catalog_publisher;
#[cfg(test)]
mod filesystem_catalog_publisher_tests;
mod filesystem_catalog_segment;
mod filesystem_catalog_snapshot;
mod filesystem_catalog_storage;
mod filesystem_initialization_namespace;
mod filesystem_initialization_storage;
mod filesystem_platform_admission;
mod filesystem_platform_admission_error;
mod filesystem_platform_profile;
mod filesystem_publisher_authority;
mod filesystem_recovery_inventory_reader;
mod filesystem_recovery_inventory_scan;
#[cfg(all(test, unix))]
mod filesystem_recovery_inventory_tests;
mod filesystem_recovery_namespace;
mod filesystem_recovery_next_head_candidate;
mod filesystem_recovery_next_head_finalization_open_error;
mod filesystem_recovery_next_head_finalization_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_next_head_finalization_tests;
mod filesystem_recovery_next_head_finalizer;
mod filesystem_recovery_segment_resume_open_error;
mod filesystem_recovery_segment_resume_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_segment_resume_tests;
mod filesystem_recovery_segment_resumer;
mod filesystem_recovery_segment_stage;
mod filesystem_recovery_stage;
mod filesystem_recovery_stage_completer;
mod filesystem_recovery_stage_completion_open_error;
mod filesystem_recovery_stage_completion_pool;
mod filesystem_recovery_stage_completion_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_completion_tests;
mod filesystem_recovery_stage_discard_open_error;
mod filesystem_recovery_stage_discard_storage;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_discard_tests;
mod filesystem_recovery_stage_discarder;
mod filesystem_recovery_stage_error;
mod filesystem_recovery_stage_error_display;
mod filesystem_recovery_stage_materialization;
mod filesystem_recovery_stage_sync;
#[cfg(all(test, unix))]
mod filesystem_recovery_stage_tests;
mod filesystem_root_identity;
mod filesystem_segment_stage;
#[cfg(test)]
mod filesystem_segment_stage_tests;
mod filesystem_store_initializer;
#[cfg(test)]
mod filesystem_store_initializer_tests;
#[cfg(test)]
#[path = "../../tests/segment_filesystem_stage/sandbox.rs"]
mod filesystem_test_sandbox;
mod filesystem_version_two_admission;
mod filesystem_version_two_records;
mod filesystem_writer_lock;
mod framed_blake3;
mod layout_decode_error;
mod layout_decode_error_display;
mod layout_decode_policy;
mod layout_encode_error;
mod layout_header_decoder;
mod layout_id_binary;
mod layout_id_binary_error;
mod layout_id_text;
mod layout_id_text_error;
mod layout_record;
mod layout_record_decoder;
mod layout_record_encoder;
mod layout_record_format;
mod layout_record_framing;
mod loaded_segment;
mod lower_hex;
mod opened_reusable_segment;
mod physical_pool_name;
mod publication_head_decode_error;
mod publication_head_decode_error_display;
mod publication_head_decoder;
mod publication_head_encoder;
mod recovery;
#[cfg(feature = "repository-tasks")]
mod repository_initialization_storage;
mod retention;
mod sealed_segment;
mod segment_digest;
mod segment_digest_builder;
mod segment_header;
mod segment_header_admission;
mod segment_header_decoder;
mod segment_header_encoding;
mod segment_header_error;
mod segment_header_error_display;
mod segment_identity_index;
mod segment_publication;
mod segment_publication_error;
mod segment_read_error;
mod segment_read_error_display;
mod segment_read_policy;
mod segment_reader;
mod segment_record_admission;
mod segment_record_admission_error;
mod segment_record_admission_error_display;
mod segment_record_checksum;
mod segment_record_cursor;
mod segment_record_cursor_decode;
mod segment_record_decode_error;
mod segment_record_decode_error_display;
mod segment_record_decoder;
mod segment_record_header;
mod segment_record_header_admission;
mod segment_record_header_decoder;
mod segment_record_header_encoding;
mod segment_record_header_error;
mod segment_record_header_error_display;
mod segment_record_identity;
mod segment_record_identity_admission;
mod segment_record_identity_encoding;
mod segment_record_kind;
mod segment_record_length;
mod segment_record_limit;
mod segment_record_payload_length;
mod segment_records;
mod segment_seal;
mod segment_seal_admission;
mod segment_seal_builder;
mod segment_seal_decoder;
mod segment_seal_encoding;
mod segment_seal_envelope;
mod segment_seal_envelope_admission;
mod segment_seal_error;
mod segment_seal_error_display;
mod segment_seal_hash;
mod segment_stage;
mod segment_stage_create_error;
mod segment_stage_create_error_display;
mod segment_stage_write;
mod segment_write_error;
mod segment_write_error_display;
mod segment_write_phase;
mod staged_segment;
mod storage_profile_id_text;
mod storage_profile_id_text_error;
mod store_initialization;
mod store_initialization_error;
mod store_initialization_phase;
mod store_initialization_receipt;
mod store_initialization_storage;
mod store_migration;
mod sync_capable_directory;
#[cfg(test)]
#[path = "../../tests/support/mod.rs"]
mod test_support;
mod writer_lock_acquire_error;
mod writer_lock_acquire_phase;

pub use exports::*;

use catalog_encoding_entry::CatalogEncodingEntry;
use catalog_entries::CatalogEntries;
use catalog_record_binding::CatalogRecordBinding;
use decoded_catalog_entry::DecodedCatalogEntry;
